### ISSUE TITLE
Simple exemple

### ISSUE THREAD

**Issue by Bio-data-tricks** [aktgpt/brevis#1]
Hi, 
I would like to use brevis on my cell cultures and tissue sections. But I don't know where to start...
Is there a notebook or something like that for reproduce the methodology and figures from your paper? 
Several errors stop the code. 

Thank you 

Nicolas

**Comment by aktgpt** [comment]
Hi,
We didn't use notebooks for the model training. As we had different methodologies for the different fluorescence channels and compared several architecture choices, it was easier to run things more directly through python, modifying the config files accordingly for each case. However, the code we provide here in BREVIS is quite modular, so it should be possible to modify the various parts as needed for different use cases. The first thing to do is to make sure your data is structured in the way specified in the README file. After that, you should change the config files to specify the data location, models, and architecture specifications you want to explore.

**Comment by Bio-data-tricks** [comment]
Hi, 
Thank you for your response. 
I have many errors in the code, does it work on your computer? 

Nicolas

**Comment by aktgpt** [comment]
Hi,

Yes, of course, it works on our computers! 

Please make sure that you have done everything in the checklist provided below: 

- Do you have the necessary libraries installed? Unfortunately, we didn't provide the list of necessary libraries in the README, so here they are: 
```
albumentations
matplotlib
numpy
opencv-python
pandas
pillow
torch
torchvision
scikit-image
scikit-learn
scipy
seaborn
tqdm 
```
- Did you change the data structure of the dataset to match ours?
- Did you make the CSV files in `exp_stats` similar to what we have provided?
- Did you change the config files so that all the information is correct according to the experiment that you want to run?

Please go through this checklist, and if you still face any errors, let us know via email.

**Comment by Bio-data-tricks** [comment]
Hi, 
Sorry but I can't get the code to work. 
I got the example file from the Adipocyte Cell Imaging Challenge, I have in input 7 images. (The 7 images are in the file adipocyte_data/60x images and the file names are the same as the origin).
In the nuclei train json i put the "run_mode" to "test" and the path to the model "test": {
        "tester": "LUPITester",
        "model_path": "C:\\Users\\goff0007\\Desktop\\brevis-master\\pre-trained_models\\C3_60x.pth"}

what am I supposed to do next ? 

Thank you 

Nicolas
